environment: "cairos_sbrc2026"

datasets:
        CIFAR-10: 
                classes: 10
                features: 32,32,3
        MNIST: 
                classes: 10
                features: 32,32,3
        FMNIST:
                classes: 10
                features: 32,32,3
        SIGN: 
                classes: 43
                features: 32,32,3
simulation:
        cars: 5
        mobility:
                distance:
                        x: 1000
                        y: 1000       
                repetitions: 3
        communication:
                repetitions: 10
        speed:
                index: 
                        - 0
                value:
                        - 13.88889 # 50 km/h
        federated_learning:
                framework: "torch"
                data:
                        alpha: "5.0"
                server:
                        ip: "127.0.0.1"
                        port: "8081"
                        timeout: 50
                        rounds: 3
                        n_clients_fit: 5
                        strategy: "cairos_pe"
                        epochs_distribution: "equal"
                client:
                        model: "RESNET10"
                        epochs: 5
                        dataset: "CIFAR-10"
        base_station:
                range: 10000
                positions: "communication/base_stations.csv"

