environment: "cairos"

datasets:
        CIFAR-10: 
                classes: 10
                features: 32,32,3
        MNIST: 
                classes: 10
                features: 32,32,3
        FMNIST:
                classes: 10
                features: 32,32,3
        SIGN: 
                classes: 43
                features: 32,32,3
simulation:
        cars: 5
        mobility:
                distance:
                        x: 1000
                        y: 1000       
                repetitions: 3
        communication:
                repetitions: 10
        speed:
                index: 
                        - 0
                value:
                        - 13.88889 # 50 km/h
        federated_learning:
                server:
                        epochs: 10
        base_station:
                range: 1200
                positions: "communication/base_stations.csv"

